name: Dee Dirosa âŒ˜ 
markdown: redcarpet
highlighter: pygments
url: http://dirosa.me
paginate: 8
description: game dev, optimism, intersectionalism & atlanta
intro: game dev, optimism, intersectionalism & atlanta
logo:             logo.png
disqus_shortname:
# url: http://gotchacode.com
#Comment out url when working locally to resolve base urls correctly
#url:

# Owner/author information
owner:
  name:           <your-name-here>
  avatar:         <avatar-image-link>
  email:          <your-email-address>
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  github:
  stackexchange:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
